### ISSUE TITLE
Bolinas traffic simulation: missing a directory /od_csv

### ISSUE THREAD

**Issue by nanma3214** [cb-cities/spatial_queue#1]
Issue at `spatial_queue/projects/bolinas_civic/run_traffic_simulation.py` line 142: no directory named `od_csv` under the folder `demand_inputs`. The issue can be resolved if we create the missing directory, so future git pulls won't encounter this problem

**Comment by bz247** [comment]
Thank you! I have updated the instructions in the README.md file, so that the missing folder will be generated before running the code. 

`mkdir -p demand_inputs/od_csv`

**Comment by nanma3214** [comment]
Sweet! Thanks for responding so quickly!
